---
# Copy to inventories/production/ and fill secrets (use ansible-vault).
all:
  children:
    proxmox_api:
      hosts:
        localhost:
          ansible_connection: local
    vyos_gateway:
      hosts:
        vyos:
