---
vyos_wan_if: "eth0"
vyos_lan_if: "eth1"
vyos_lan_ipv4: "192.168.1.1"
vyos_lan_prefix: "24"
vyos_lan_network: "192.168.1.0/24"
vyos_dhcp_range_start: "192.168.1.100"
vyos_dhcp_range_stop: "192.168.1.250"
vyos_dhcp_shared_network: "LAN"

phase1_dns_provider: "cloudflare"

phase1_dns_map:
  cloudflare:
    - "1.1.1.1"
    - "1.0.0.1"
  opendns:
    - "208.67.222.222"
    - "208.67.220.220"
